### PR TITLE
fixed a sbt plugin bug / added example and documentation on how to use the plugin fixes #99

### LINKED ISSUE #99: Example and documentation of the usage of the sbt plugin

### PR DESCRIPTION
**Pull request by kailuowang**
also added the ability to set swggerFileName and swaggerRoutesFile in sbt

### CODE REVIEW

File: sbtPlugin/src/main/scala/com/iheart/sbtPlaySwagger/SwaggerPlugin.scala [hunk 1]
```diff
@@ -24,19 +23,25 @@ object SwaggerPlugin extends AutoPlugin {
 
   override def projectSettings: Seq[Setting[_]] = Seq(
     ivyConfigurations += swaggerConfig,
+    //todo: remove hardcoded org name using BuildInfo
     libraryDependencies += "com.iheart" %% "play-swagger" % playSwaggerVersion % swaggerConfig,
     swaggerDomainNameSpaces := Seq(),
-    swaggerTarget := "public/swagger.json",
+    swaggerTarget := target.value / "swagger",
```
Comment (joprice) [inline sbtPlugin/src/main/scala/com/iheart/sbtPlaySwagger/SwaggerPlugin.scala]: I like these extra keys.

**Comment by joprice** [comment]
Looks good. I like how more strings are configurable. 👍
