### PR TITLE
Fixing generation of string default parameters

### LINKED ISSUE #134: Default string params are double quoted in swagger.json
I have a route that has a default string value, e.g.,

```
GET /config   controllers.MyController.getConfig(location: String ?= "US")
```

In the generated swagger.json file, the default value is double quoted:

``` json
{
    "parameters": [{
        "in": "query",
        "name": "location",
        "type": "string",
        "required": false,
        "default": "\"US\""
    }]
}
```

this causes the input field in swagger-ui to have the quotes in it, instead of just `US`

### PR DESCRIPTION
**Pull request by mtrovo**
Fixes #134 
The parameter mapper from default value string seems a bit hacky but
it seems to be the right way to handle it, I talked with some 
maintainers on playframework and strangely they always get this value
as literal, which means there's no nice way to convert this to the
correct parameter type.

### CODE REVIEW

File: core/src/main/scala/com/iheart/playSwagger/SwaggerParameterMapper.scala [hunk 1]
```diff
@@ -34,7 +34,11 @@ object SwaggerParameterMapper {
           case ci"Int" | ci"Long"                      ⇒ JsNumber(value.toLong)
           case ci"Double" | ci"Float" | ci"BigDecimal" ⇒ JsNumber(value.toDouble)
           case ci"Boolean"                             ⇒ JsBoolean(value.toBoolean)
-          case _                                       ⇒ JsString(value)
+          case ci"String" ⇒ {
+            val noquotes: String = "^(?:\"|\"\"\")?(.*?)(?:\"|\"\"\")?$".r.replaceAllIn(value, "$1")
```
Comment (kailuowang) [inline core/src/main/scala/com/iheart/playSwagger/SwaggerParameterMapper.scala]: Do you mind adding more test cases for this regex replace?

**Comment by kailuowang** [comment]
sorry for the late response. I've been on vacation recently.

**Comment by kailuowang** [comment]
@mtrovo any interest to continue this great PR?

**Comment by mtrovo** [comment]
@kailuowang at this time it was me that was on vacation, I'm adding more tests in a new commit 👍

**Comment by kailuowang** [comment]
thanks @mtrovo !

**Comment by kailuowang** [comment]
looking good to me! Thanks very much @mtrovo
